export const SELECT_RSS_FEED = "SELECT_RSS_FEED";
export const ADD_ERROR_MESSAGE = "ADD_ERROR_MESSAGE";
export const DISMISS_ERROR_MESSAGE = "DISMISS_ERROR_MESSAGE";
export const ADD_NEW_RSS_FEED_DETAILS = "ADD_NEW_RSS_FEED_DETAILS";
export const UPDATE_RSS_FEEDS = "UPDATE_RSS_FEEDS";
export const SELECT_RSS_FEED_TAG = "SELECT_RSS_FEED_TAG";
export const TOGGLE_IS_LOADING_FEED = "TOGGLE_IS_LOADING_FEED";
